// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYETdr75ZoG-ePijVyBlxBWdaEUZ4UmJg',
    appId: '1:206255218677:web:b8bfcb69ac6a8a530bcabc',
    messagingSenderId: '206255218677',
    projectId: 'movieapp-eae22',
    authDomain: 'movieapp-eae22.firebaseapp.com',
    storageBucket: 'movieapp-eae22.appspot.com',
    measurementId: 'G-VM7VLWHJKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHB1tocUR3vlk6pIdBmimqzSGS4CkI7M',
    appId: '1:206255218677:android:0b44c61f44fc8f580bcabc',
    messagingSenderId: '206255218677',
    projectId: 'movieapp-eae22',
    storageBucket: 'movieapp-eae22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DW4hbBmWHYmPwMJ6PJ795TMMPbnxgoI',
    appId: '1:206255218677:ios:6ec4fd75a9ad2c9f0bcabc',
    messagingSenderId: '206255218677',
    projectId: 'movieapp-eae22',
    storageBucket: 'movieapp-eae22.appspot.com',
    iosClientId: '206255218677-300bvcjr95695usmp0pm2tavpqaublj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemamovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DW4hbBmWHYmPwMJ6PJ795TMMPbnxgoI',
    appId: '1:206255218677:ios:d03f5cfd809a58100bcabc',
    messagingSenderId: '206255218677',
    projectId: 'movieapp-eae22',
    storageBucket: 'movieapp-eae22.appspot.com',
    iosClientId: '206255218677-man71omem7pis6mug2jvj80du51bjq3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemamovie.RunnerTests',
  );
}
